name: Liste des fichiers au Push

on: [push]

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      # Maintenant que le code est là, on peut le lister
      - name: Afficher la liste des fichiers
        run: ls -R