name: Check Tree on PR

# Déclencheur : Uniquement lors d'une Pull Request vers main ou master
on:
  pull_request:
    branches: [ main, master ]

jobs:
  verify-structure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Exécuter la vérification d'arborescence
        run: php C:/Users/Louki/projet_git/.github/scripts/check_tree.php