name: E2E Tests with TestCafe

on: [push, pull_request]

jobs:
  testcafe-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run TestCafe
        run: |
          npx testcafe "chrome:headless" tests/test_use_case.js \
          --app "php -S localhost:8080" \
          --app-init-delay 5000